- Mage/Command/BuiltIn/DeployCommand.php
fix: DeployCommand does not fail when no one "Post-Deployment Tasks" failed and failed "Deployment Task" exist
> fix: DeployCommand does not fail after failed "Deployment Task"

- Mage/Task/BuiltIn/Filesystem/ApplyFaclsTask.php
Make `ApplyFaclsTask` compatible with default `AbstractTask::runCommandRemote()` parameter  `$cdToDirectoryFirst=true`.
When a relative path is given in `deployment -> to`, the task will first `cd` into this directory and then also prepend that path to the `setfacl` argument. One of these is enough. (This is true also for absolute paths given in `deployment -> to`, but will not case `setfacl` to fail.)
> fix bug in ApplyFaclsTask due to $cdToDirectoryFirst=true

- .gitignore
- composer.json
- composer.lock
- phpunit.xml.dist
- tests/MageTest/Console/ColorsTest.php
Hey,
As I mentioned in #159 , I've done some fixes and corrections for PHPUnit test environment for Magallanes. I've also noticed and fixed following problems:
* lack of `phpunit` in `bin` directory while doing installing dependencies by composer. I've fixed that by adding `bin-dir` to `composer.json`
* no colors... for phpunit output :) Changed phpunit default configuration in `phpunit.xml.dist`
* coverage - I've added `coversDefaultClass` and `covers` in test class to be sure that those test methods test that what we want to test
Please free to code-review!
@SenseException @andres-montanez 
PS. Sorry, I had to close previous PR, because I accidentally compared it to `master` branch again :(
> Fixes #159: PHPUnit tests tuning

- CONTRIBUTING.md
I did some minor fixes of typos and a few changes of sentences. Nothing big, since the contribution guide is already a good starter and will grow over time.
I've added the PHP Coding Standards Fixer to the tools, since this may be useful for some developers.
> Typos and sentences fixed in contribution guide

- Mage/Task/BuiltIn/Deployment/Strategy/GitRebaseTask.php
I've brought back some piece of code removed in https://github.com/andres-montanez/Magallanes/commit/92b22d52a3603b2b7c8f22b3baadc470ecb3bc36#diff-81da38bff73f46a53c72da138abfb492
GitRebase strategy deployment was failing if relases were enabled because Magallanes was trying to `cd` to directory that didn't exist.
> Create release directory for GitRebase strategy

- .coveralls.yml
- .travis.yml
- composer.json
- composer.lock
Hi all!
This PR introduces **travis-ci** and **coveralls.io** support as it has been proposed in #163.
Actually there was a config for travis, but I've modified it by:
* removing `--dev` flag in `composer install` since it's the default option when running `composer install`
* add scripts necessary to trigger coveralls report
I needed to add `php-coveralls` package to composer to run Coveralls reporting. I've also add `.coveralls.yml` to override default options of coveralls build.
**Since I'm not the owner of this repo, @andres-montanez, please turn it on in repo management panel on travis-ci.org and coveralls.io before or just after merging this PR**. I've tested both on my fork and everything build with success.
> Add Travis and Coveralls support

- Mage/Task/BuiltIn/Deployment/ReleaseTask.php
- Mage/Task/BuiltIn/Deployment/Strategy/RsyncTask.php
Fix 2 problems leading to a 1st deploy failure (one only with rsync strategy and the other more widely I think)
In `ReleaseTask.php`, we're trying to change owner of symlink file. But on first release the symlink does not exists yet so the release fail (problem comes from #178 I think). I've updated to only check owner if symlink exists. (maybe we can remove totaly the symlink owner check as it's created after ?)
In `RsyncTask.php`, with `rsync_copy` enabled, if the previous release folder does not exists, the release directory is not created, and rsync fail. I've updated to revert to manual empty directory creation if there is no previous release.
> Fix 1st deploy bug

- Mage/Task/BuiltIn/Deployment/Strategy/TarGzTask.php
This pull requests fixed #202 issue.
Remove inconsistency between `ssh` and `scp` commands. As @kaiwa noticed, `UserKnownHostsFile` and `StrictHostKeyChecking` ssh options were not set when running `scp` command, what may cause problems when running them.
**To be done**: Let `UserKnownHostsFile` and `StrictHostKeyChecking` options be configurable (#105)
> Add UserKnownHostsFile and StrictHostKeyChecking options to scp command

- Mage/Command/AbstractCommand.php
- Mage/Command/BuiltIn/CompileCommand.php
- Mage/Command/BuiltIn/ListCommand.php
- Mage/Command/BuiltIn/LockCommand.php
- Mage/Command/BuiltIn/UnlockCommand.php
- composer.json
- composer.lock
- tests/MageTest/Command/AbstractCommandTest.php
- tests/MageTest/Command/BuiltIn/CompileCommandTest.php
- tests/MageTest/Command/BuiltIn/ListCommandTest.php
- tests/MageTest/Command/BuiltIn/LockCommandTest.php
- tests/MageTest/Command/BuiltIn/UnlockCommandTest.php
- tests/MageTest/TestHelper/BaseTest.php
Hey there!
This PR introduces tests of few commands including:
* `AbstractCommand`
* `CompileCommand`
* `ListCommand`
* `LockCommand`
* `UnlockCommand`
These tests cover the code in 100% (line coverage) without changing current functionality.
Few words about PR:
* I used [malkusch\php-mock](https://github.com/malkusch/php-mock) for creating mocks of PHP's built-in functions. As far as I know, it uses the fact that PHP interpreter will use the function with the same name from the namespace where it was used in. This library contains some other cool options like making **stubs** on built-in functions but since we're keeping compatibility with PHP 5.3, we can't use them and we can just mock them to avoid unexpected results. Fortunatelly, author created the `php-5.3` branch.
* I had to use …
> Add commands tests

- bin/mage
If the timezone is set in the php cli ini file, mage should use that one instead of the default UTC
> The timezone should be system dependent

- Mage/Task/AbstractTask.php
- Mage/Task/BuiltIn/Deployment/ReleaseTask.php
- Mage/Task/BuiltIn/Deployment/Strategy/RsyncTask.php
- Mage/Task/BuiltIn/Releases/RollbackTask.php
when releasing or rolling back, don’t chown the »current« symlink before we changed / created it.
also don’t screw up the ssh cmdline if no username was given.
> don’t fail the initial deployment to a target, and allow ssh without a username

- composer.json
- composer.lock
Hi
I moved the package `malkusch/php-mock` to [`php-mock/php-mock`](https://github.com/php-mock/php-mock).
> malkusch/php-mock moved to php-mock/php-mock

- bin/mage
The bin/mage script returns "Can't use function return value in write context" in php<5.5
> Fixing a little bug in php<5.5

- Mage/Task/BuiltIn/Deployment/ReleaseTask.php
If the "owner" is specified in environment configuration, the resultFetch value is never changed from false to true. Therefore checking for that before setting permissions is pointless.
> resultFetch is always false when owner is specified in config

- Mage/Command/AbstractCommand.php
- Mage/Command/BuiltIn/AddCommand.php
- Mage/Command/BuiltIn/CompileCommand.php
- Mage/Command/BuiltIn/DeployCommand.php
- Mage/Command/BuiltIn/InitCommand.php
- Mage/Command/BuiltIn/InstallCommand.php
- Mage/Command/BuiltIn/ListCommand.php
- Mage/Command/BuiltIn/LockCommand.php
- Mage/Command/BuiltIn/ReleasesCommand.php
- Mage/Command/BuiltIn/RollbackCommand.php
- Mage/Command/BuiltIn/UnlockCommand.php
- Mage/Command/BuiltIn/UpdateCommand.php
- Mage/Command/BuiltIn/UpgradeCommand.php
- Mage/Command/BuiltIn/VersionCommand.php
- Mage/Console.php
- tests/MageTest/Command/AbstractCommandTest.php
- tests/MageTest/Command/BuiltIn/CompileCommandTest.php
- tests/MageTest/Command/BuiltIn/ListCommandTest.php
- tests/MageTest/Command/BuiltIn/LockCommandTest.php
- tests/MageTest/Command/BuiltIn/UnlockCommandTest.php
- tests/MageTest/Command/BuiltIn/VersionCommandTest.php
Hi Magallanes users! Welcome back after such long break :)
Some time ago I've started working on `--help` option for commands. I don't know why I have stopped contributing this idea. Fortunatelly, I've got everything on remote repo on my GitHub account, so I could continue my work :)
This PR includes only part of `--help` functionality. After running Magallanes binary with command and `--help` option, you should get description of the command such as that on following screenshot:
There is much more to do than I thought before. Things that should be done in the nearest future includes:
* General `--help` for `mage` binary
* Option to specify command arguments and options (like in Symfony2 commands) to validate command calling and generate help message dynamically and avoid programmers …
> Handle '--help' option for commands

- Mage/Command/BuiltIn/DeployCommand.php
Changing order of the 'scm/change-branch' task to be the last task executed on post deployment stage.
This change allows to execute current branch tasks on post deployment stage.
> Set branch revert as the last task on post deployment

- README.md
“~1.0.*” results in a Composer throwing an UnexpectedValueException
> Fix Composer version constraint

- Mage/Task/BuiltIn/Deployment/ReleaseTask.php
Sometimes remote command "ls -ld ." returns unwanted line(s). In my case it was returning "Identity added..." which is caused by ProxyCommand config (which I need in my environment). I've added some codes to detect and remove this.
Example from log that illustrate the issue:
2016-12-26 05:45:01 -- ---------------------------------
2016-12-26 05:45:01 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@host "sh -c \"cd /path/to/dir && ls -ld .\""
2016-12-26 05:45:05 -- Identity added: /home/user123/.ssh/id_rsa (/home/user123/.ssh/id_rsa)
drwxr-xr-x 6 deployuser deployuser 4096 Dec 26 18:33 .
2016-12-26 05:45:05 -- ---------------------------------
The output from remote server was:
Identity added: /home/user123/.ssh/id_rsa …
> Detect and remove "Identity added:" line from the remote server.

- Mage/Command/BuiltIn/DeployCommand.php
If `runDeploymentTasks()` failed, `runNonDeploymentTasks()` resets the `failedTasks` count. This causes the wrong exit code to be returned by mage.
> Don't prematurely reset failedTasks count

- Mage/Command/BuiltIn/DeployCommand.php
Fixing the bug reported in #292
> 292: Notification email reports SUCCESS even if deployment failed

- Mage/Task/BuiltIn/Scm/ChangeBranchTask.php
This is necessary to save to reverse back to the right branch if another branch is used than 'master' and you´re currently working in the deployed branch.
> Change the point the current branch is saved.

- Mage/Task/BuiltIn/Deployment/Strategy/TarGzTask.php
Allow wildcard in excludes configuration:
``` yml
deployment:
...
excludes:
- ./src/*/Tests
- docker-compose.yml
```
will generate :
`tar cfz /tmp/mageTeVWVI.tar.gz  --exclude="./src/*/Tests" --exclude=docker-composer.yml -C ./ .`
> Escape targz excludes to allow wildcard

- src/Task/BuiltIn/Deploy/RsyncTask.php
- src/Task/BuiltIn/Deploy/Tar/PrepareTask.php
When empty lines are left in the "exclude" list, RSync is still sending `--eclude=` with empty excluded items
> Rsync task: ignore empty 'exclude' parameters

- src/Task/BuiltIn/Composer/SelfUpdateTask.php
- tests/Command/BuiltIn/Composer/SelfUpdateTaskTest.php
This is a PR for https://github.com/andres-montanez/Magallanes/issues/332.
Provides `composer selfupdate` which is not executed if the version is not older than `30` days which is configurable through the `days` option 😎
> Added composer selfupdate command

- src/Task/BuiltIn/ExecTask.php
- tests/Command/BuiltIn/ExecTaskTest.php
This is a PR for https://github.com/andres-montanez/Magallanes/issues/336.
Usage:
```yml
- exec { cmd: 'my command' }
```
If you like, you can pass a custom description like so:
```yml
- exec { cmd: 'my command', descr: 'My command does this and that' }
```
Also you can `jail` it (which forces remote execution) and adjust the `timeout`. 😎
> Added task to execute arbitrary commands

- src/Task/BuiltIn/Composer/InstallTask.php
It's not unusual, depending on your environment, for Composer's install command to exceed the default 120 second timeout value. This allows you to configure that value and keeps the default 120 second value otherwise.   
Usage:  
```
magephp:
environments:
production:
pre-deploy:
- composer/install: { timeout: 600 }
[...]
```
> [FEATURE] Added support for specifying task timeout in composer install task

- src/Task/BuiltIn/Deploy/RsyncTask.php
- src/Task/BuiltIn/Deploy/Tar/PrepareTask.php
- tests/Command/BuiltIn/DeployCommandMiscTasksTest.php
- tests/Resources/global-exclude.yml
Hi,
I've allowed the exclude definition to be globally defined. My Configuration uses on every environment the same excludes and so i must implement duplicate code. With this feature i define the excludes only one time. 
Now its both possible global and environment specific
Example: tests/Resources/global-exclude.yml
> [FEATURE] allow exclude definition global

- src/Task/BuiltIn/Symfony/AsseticDumpTask.php
- tests/Runtime/RuntimeMockup.php
- tests/Task/BuiltIn/Symfony/AsseticDumpTaskTest.php
Adds a timeout option for the assetic:dump task.
This gives the possibility to overwrite the default timeout (120 seconds) for a long running assetic:dump processes.
> [FEATURE] Add timeout option for assetic:dump task

- src/Runtime/Runtime.php
- tests/Runtime/RuntimeTest.php
Support configure different ports on same host in `host:port` notation.
> [FEATURE]Support colon notation in host config definition

- src/Runtime/Runtime.php
- src/Task/BuiltIn/Deploy/Tar/CopyTask.php
- tests/Command/BuiltIn/DeployCommandWithReleasesTest.php
- tests/Resources/testhost-with-release-timeout.yml
**Use case:**
Deploying using releases will copy the tar archive to the remote server with "scp command" with a timeout maximum of 300 seconds .
**Problem:**
If you have limited upload bandwidth and/or big tar archives, the command will run into a timeout after 300 seconds.
$process = $this->runtime->runLocalCommand($cmdCopy, 300);
**Solution:**
Make the timeout for the CopyTask (scp upload command) configurable in the .mage.yml file. The default value can still be 300 seconds.
> Make CopyTask scp command timeout configurable

- src/Task/BuiltIn/Deploy/Tar/PrepareTask.php
Under Windows, we need the `--force-local` argument for `tar_create` by default. Otherwise, due to the `:` in absolute Windows file paths, tar thinks that the path is on another machine - and you have to override this using `--force-local` (see also https://github.com/Microsoft/azure-pipelines-tool-lib/issues/34 for example).
Imho it is important to integrate this into Magallanes, so that a `.mage.yml` can be committed to a git repository and then used by Linux and Windows users alike. Otherwise if you put
```yml
tar_create: --force-local -c -z -p -f
```
into your `.mage.yml` it will not work for *nix users anymore - and without it it won't work for Windows users.
> fix tar_create command on Windows

- src/Command/BuiltIn/Releases/ListCommand.php
- src/Command/BuiltIn/Releases/RollbackCommand.php
- src/Task/BuiltIn/Composer/SelfUpdateTask.php
- src/Task/BuiltIn/Deploy/Release/CleanupTask.php
- tests/Runtime/ProcessMockup.php
This fixes #428 
Currently Magallanes uses `PHP_EOL` for every instance where it wants to either parse or write a new 'new line character'.
However, when Magallanes is used on Windows, this breaks things like the `CleanupTask` (see #428) - if the remote host is a Unix machine (which it usually is).
The proposed solution isn't perfect and simply assumes, that the remote host will always be a Unix machine.
May be the __remote__ EOL character should be made configurable in the `.mage.yml` and simply defaults to `"\n"` otherwise. What do you think?
> [RFC] do not use PHP_EOL for remote data

- src/Task/BuiltIn/SleepTask.php
- tests/Task/BuiltIn/SleepTaskTest.php
Sometimes that's helpful, like if you have to wait a few moments until e.g. the `current` symlink is ready and the server was able to update internally etc.
> Added sleep task to allow delaying execution of other tasks
